allowBuilds:
<<<<<<< HEAD
  '@parcel/watcher': set this to true or false
  unrs-resolver: set this to true or false
  vue-demi: set this to true or false
=======
  '@parcel/watcher': true
  unrs-resolver: true
  vue-demi: true
>>>>>>> c27dc311feeca88f575184c70cd539091ffeaf47
